uint8 CLEAR_NIGHT=0
uint8 CLEAR_NOON=1
uint8 CLEAR_SUNSET=2
uint8 CLOUDY_NIGHT=3
uint8 CLOUDY_NOON=4
uint8 CLOUDY_SUNSET=5
uint8 DEFAULT=6
uint8 DUST_STORM=7
uint8 HARD_RAIN_NIGHT=8
uint8 HARD_RAIN_NOON=9
uint8 HARD_RAIN_SUNSET=10
uint8 MID_RAIN_SUNSET=11
uint8 MID_RAINY_NIGHT=12
uint8 MID_RAINY_NOON=13
uint8 SOFT_RAIN_NIGHT=14
uint8 SOFT_RAIN_NOON=15
uint8 SOFT_RAIN_SUNSET=16
uint8 WET_CLOUDY_NIGHT=17
uint8 WET_CLOUDY_NOON=18
uint8 WET_CLOUDY_SUNSET=19
uint8 WET_NIGHT=20
uint8 WET_NOON=21
uint8 WET_SUNSET=22

uint8 weather 6
---
bool result
string message
